# Site settings
title: Sun Dream
email: mentary.fransiska@gmail.com
url: https://mentary.github.io
description: "I am a student of information system at faculty sains and technology at state of islamic university of sultan syarif kasif riau ."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/@FarizaRaisa
  - title: facebook
    url: https://facebook.com/mentary.fransiska
  - title: instagram
    url: http://instagram.com/mentaryfransiska
  - title: github
    url: https://github.com/mentary
  - title: linkedin
    url: https://linkedin.com/mentary fransiska
  - title: slideshare
    url: https://slideshare.net/mentaryfransiska

# Build settings
markdown: kramdown
permalink: pretty
